### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by carcaschoi** [yanisdreemurr/ShallowSea-Fork#1]
A nice fork😄, seem that I need to update English translation of my main project🤣🤣

ldn_mitm problem:
The official build of ldn_mitm doesn't support 0.19.2/0.19.3 so I try the beta build : https://github.com/spacemeowx2/ldn_mitm/issues/91#issuecomment-837574818 

It seems that have error too. So I give up to update it😅. If you want to use ldn_mitm, you must use it with 0.19.1 or lower

**Comment by yanisdreemurr** [comment]
Okay, thanks for the information (indeed, I come to retest, I have a fatal error, so I will test with the beta version)  and thanks for the compliment haha! xD
